<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="user-PC" name="com.actitime.genericlib.Testannotationprogram2" tests="2" failures="0" timestamp="10 Nov 2019 20:38:14 GMT" time="0.031" errors="2">
  <testcase name="modifycustomertest" time="0.000" classname="com.actitime.genericlib.Testannotationprogram2">
    <error type="java.lang.Throwable" message="Method Testannotationprogram2.modifycustomertest()[pri:0, instance:com.actitime.genericlib.Testannotationprogram2@6a03af] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method Testannotationprogram2.modifycustomertest()[pri:0, instance:com.actitime.genericlib.Testannotationprogram2@6a03af] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1039)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- modifycustomertest -->
  <testcase name="createcustomertest" time="0.031" classname="com.actitime.genericlib.Testannotationprogram2">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at com.actitime.genericlib.Testannotationprogram2.createcustomertest(Testannotationprogram2.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- createcustomertest -->
</testsuite> <!-- com.actitime.genericlib.Testannotationprogram2 -->
